version: "3.3"

services:
  bot:
    build: .
    environment:
      DB_URI: '${DB_URI}'
      TOKEN: '${TOKEN}'
      DEBUG: '${DEBUG}'
    restart: always
    logging:
        options:
            max-size: 1m
